version: '3.7'
services:
    inazuma_backend:
        container_name: inazuma_backend
        image: inazuma_backend
        ports:
            - '8080:8080'
        restart: always
        networks:
            - inazuma_network
        build:
            context: ./
            dockerfile: Dockerfile
    caddy:
        container_name: inazuma_caddy
        image: caddy:latest
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./scripts/caddy_data:/data
            - ./scripts/caddy_config:/config
            - ./scripts/caddy_config/Caddyfile:/etc/caddy/Caddyfile
        networks:
            - inazuma_network
            - public_access

networks:
    public_access:
    inazuma_network:
        name: inazuma_network
        driver: bridge

