name: Backend deploy

on: 
  push:
    branches: ['*']

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Build and Deploy Docker
        working-directory: ./apps/backend
        run: |
          chmod +x ./scripts/cicd.sh
          ./scripts/cicd.sh