name: Backend deploy

on: 
  push:
    branches: 
      - main
    paths:
      - 'apps/backend/**'

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Create Env File
        run: |
          touch ./apps/backend/.env
          echo ESTUARY_API_KEY=${{secrets.ESTUARY_API_KEY}} >> ./apps/backend/.env
          echo FG_TOKEN=${{secrets.FG_TOKEN}} >> ./apps/backend/.env
          echo INFURA_API_KEY=${{secrets.INFURA_API_KEY}} >> ./apps/backend/.env
          echo PK=0x${{secrets.PK}} >> ./apps/backend/.env
          echo PKI=${{secrets.PK}} >> ./apps/backend/.env
          echo ADDRESS=${{secrets.ADDRESS}} >> ./apps/backend/.env
          echo MNEMONIC=${{secrets.MNEMONIC}} >> ./apps/backend/.env
          echo TONCENTER_API_KEY=${{secrets.TONCENTER_API_KEY}} >> ./apps/backend/.env

      - name: Build and Deploy Docker
        working-directory: ./apps/backend
        run: |
          chmod +x ./scripts/cicd.sh
          ./scripts/cicd.sh